#!/bin/bash
# autor: Pep Diz
# licencia: GPL v2

# consideraciones de disenho:
# - no se permiten ficheros ocultos (.*), se ignoran
# - no se guarda el contenido de los directorios, solo su nombre
# - cada fichero puede tener asociado un fichero oculto .info con metadatos
#     ej, el fichero arduino.zip puede tener un .arduino.zip.info
# - el repositorio se guarda en un fichero de nombre .repo

function leerinfo {
  local f=$1
  DES=''
  CAT='' 
  VER=${f#*.}
  [ -f $f.info ] && . $f.info
}


REPOFIC=.repo
REPOFILTRO="grep -v '^.+\.info' | grep -v $REPOFIC"
FILTRO="cat"
[ -f .repo-ignore ] && FILTRO="grep -E -v -f .repo-ignore"

ls -1 | eval $REPOFILTRO | $FILTRO | while read f ; do
  [ -d "$f" ] && TIPO=d || TIPO=f
  MD5=$(md5sum "$f" | cut -d\  -f 1)
  leerinfo "$f"
  echo "$TIPO:$MD5:$f:$VER:$DES:$CAT"
  echo "$TIPO:$MD5:$f:$VER:$DES:$CAT" >> REPOFIC
done

